{
 "title": "KubeSentinel",
 "time": { "from": "2025-10-09T05:11:07.889Z", "to": "2025-10-10T05:11:07.889Z" },
 "panels": [
  {
   "title": "Cluster CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total[2m])) / 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[2m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[2m])) by (pod)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(node_filesystem_avail_bytes) / sum(node_filesystem_size_bytes) * 100)",
     "legendFormat": "Cluster Disk Usage %"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Top 5 pods by Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum(container_memory_working_set_bytes) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 pods by CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total[2m])) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Restarts(All Pods)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[2m]) + rate(node_network_transmit_bytes_total[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}