apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-cpu-rule
  namespace: default
  labels:
    release: monitoring
spec:
  groups:
  - name: example
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[2m])) by (pod) > 0.8
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage on pod {{ $labels.pod }}
