apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-job-cron
spec:
  schedule: "*/5 * * * *"  # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ml-job
            image: ml-job:latest
            imagePullPolicy: Never
            env:
              - name: S3_BUCKET
                value: "kubesentinel-metrics"
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_SECRET_ACCESS_KEY
              - name: AWS_DEFAULT_REGION
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_DEFAULT_REGION
          restartPolicy: Never
