apiVersion: batch/v1
kind: CronJob
metadata:
  name: prediction-watcher-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: prediction-watcher-sa
          containers:
            - name: prediction-watcher
              image: prediction-watcher:latest
              imagePullPolicy: Never
              env:
                - name: S3_BUCKET
                  value: "kubesentinel-metrics"
                - name: PREDICTIONS_KEY
                  value: "model-output/model_predictions.json"

                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_ACCESS_KEY_ID

                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_SECRET_ACCESS_KEY

                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_DEFAULT_REGION

          restartPolicy: Never
